name: Sync eSign-v2.1 Postman Collection

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the action
    paths:
      - 'assets/esign-v2.1-collection.json'
  
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  sync-postman-collection:
    uses: ./.github/workflows/sync-postman-collection.yml
    with:
      collection-uid: ${{ vars.ESIGN_COLLECTION_UID }}
      collection-path: './assets/esign-v2.1-collection.json'
    secrets:
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}